version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./sql/init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres